### ISSUE TITLE
Cannot align office chairs and mac in desire direction

### ISSUE THREAD

**Issue by chahorain** [CompbuildREDUX/Compbuild-Textures#15]
I want to create a office room, but office chairs and mac, all of them cannot align to my desired direction. The default direction is not my goal, I want them to face right, left base on my table blocks. How can I change its direction without making it leaning on any blocks?

**Comment by Compbuild** [comment]
Assume you’re playing Singleplayer, there are a couple options for this. We use WorldEdit Blockstates in order to combat this. You can use a command with WorldEdit like //set horn_coral_fan[facing=west] You can set it to any direction you’d like (NSEW)

Another (more vanilla friendly) option is to use barriers, but since you said you don’t want to use any other blocks you can probably use repeat command blocks that do a setblock command with a coordinate location with a direction blockstate.

If you have any more questions feel free to contact us on Discord :) We’ll be happy to help

**Comment by chahorain** [comment]
Thanks for the reply! I have world edit installed. Will //set horn_coral_fan[facing=west] change all the fan's direction or just a single one? I want to adjust them one by one

**Comment by Compbuild** [comment]
You can probably replace a large area with the furniture. For example you can manually place different colors of wool for the kind of block you wanna replace it with, then you can type //replace red_wool horn_coral_fan[facing=west] You can use any wool or even any block of your choice of course. 

Changing block directions also works for other blocks other than just fans (think of any block in the default pack that can be placed in various directions). Honestly you can play around with Blockstates a lot!

**Comment by chahorain** [comment]
Thank you!!!

**Comment by chahorain** [comment]
There is another problem, when I was using pure optifine, textures look good. But if I want to use worldedit like you mentioned above, I use optifabric, but some of the glass looks glitchy in one direction.
![image](https://github.com/CompbuildREDUX/Compbuild-Textures/assets/66765816/97f6f693-7d43-41e4-8e38-37229d0a1c4c)
![image](https://github.com/CompbuildREDUX/Compbuild-Textures/assets/66765816/a3d66728-66cf-4a64-bb04-c4d9140ed402)
![image](https://github.com/CompbuildREDUX/Compbuild-Textures/assets/66765816/0d3bd951-010b-427c-a732-0fe19279c757)
What happened to the texture?

**Comment by chahorain** [comment]
They look like stacking to each other in one direction, they keep z fighting forever

**Comment by Compbuild** [comment]
Unfortunately this is a problem with OptiFabric and not us. You'll have to contact OptiFabric support for this. Glass Panes also conflict with no texture pack enabled just not as noticeable, there's lines in glass. This happened to me on OptiFabric as well and I usually just ignore it, haven't reported the bug yet though.

**Comment by chahorain** [comment]
I see, I guess I would use optifabric only for world edit, and then go back to optifine for other tweaks

**Comment by chahorain** [comment]
> 

I tried to set it to facing west, but the set command only accept argument of waterlogged

**Comment by Compbuild** [comment]
Direction arguments only work on fans and blocks that have different block states you can rotate in default (think coral fans!)

**Comment by chahorain** [comment]
Oh that is begin to be complicating to me.. So should I set the original block to a certain block state and then I can change its facing direction?

**Comment by Compbuild** [comment]
No. Just set all the arguments in one command like //set horn_coral_fan[facing=west,waterlogged=false] for example. 

The **facing=** value does not work for some blocks because of vanilla limitations.

**Comment by chahorain** [comment]
That is what I found out yeah. facing is not working even under worldedit. Fan blocks seem to only accept waterlogged arguments

**Comment by chahorain** [comment]
no matter if I use replce, set or any other commands. If I want to add a facing arguments to fan block, it keeps complaining facing is an unknown argument

**Comment by Compbuild** [comment]
Oh yeah my fault for preaching about fans this entire time! Facing values should work on wall fans (with WorldEdit). If you'd like to have a coral fan a different direction have them set to wall fans instead. 

I greatly apologize for this, I was on vacation in Mexico during most of the time in this issue thread!

**Comment by chahorain** [comment]
If I select several more blocks, fan blocks can be copied and rotate. But the facing direction is not changing even after rotated
![image](https://github.com/CompbuildREDUX/Compbuild-Textures/assets/66765816/9a80c383-7896-4583-b177-7d42f6a71219)

**Comment by chahorain** [comment]
No worries at all! I am the one keep bothering you all the time and being stupid

**Comment by Compbuild** [comment]
A final solution since this is a bit complicated to explain is to use WorldEdit's rotate command. You can use **// rotate 90** on a coral that's placed on a wall and move it with selections.

**Comment by chahorain** [comment]
It finally worked, you are correct, only I create fans on a wall then I can select them and rotate them

**Comment by chahorain** [comment]
Though it is very time consuming, but worked

**Comment by chahorain** [comment]
I love you so much

**Comment by chahorain** [comment]
Life saver

**Comment by Compbuild** [comment]
<3

**Comment by chahorain** [comment]
Found another problem not sure if you have a solution: computers cannot align back to back. So I make fans on the wall and rotate them. They cannot be placed while back to back on two connecting blocks

**Comment by chahorain** [comment]
![image](https://github.com/CompbuildREDUX/Compbuild-Textures/assets/66765816/38b4ebff-1e17-41d7-9a82-21cc81b9e875)

**Comment by Compbuild** [comment]
Try using //flip ? Never encountered something like that before

**Comment by chahorain** [comment]
![image](https://github.com/CompbuildREDUX/Compbuild-Textures/assets/66765816/80c124d5-861e-40fd-a7f8-06ee652a76d3)
I am afraid the wall fan is complaining there is no walls to lean on, while they are back to back, two fans are trying to ask each other whether they are walls or not, then they break

**Comment by Compbuild** [comment]
The best thing you can probably do at that situation is use /setblock or even try the debug stick.

**Comment by chahorain** [comment]
If I destroy the computer on the right, the left one also breaks

**Comment by Compbuild** [comment]
Unfortunately that's a vanilla limitation.

**Comment by chahorain** [comment]
Yeah I understand, set block does not work sadly

**Comment by chahorain** [comment]
Or.. is there a way I can replace another block preset using json files that I am not using to mac model? That can probably solve the issue directly

**Comment by Compbuild** [comment]
You can give a shot at modifying the JSON pack models for now yourself for now, we might make some more single player guides on model rotation on our Discord later. 

If you plan to edit the pack, you can edit it for personal use but you can't distribute it publicly.

**Comment by chahorain** [comment]
Sure I won't. I tried once, only copying and pasting two mac json files in Blocks folder, but I dont know why the bottom of the mac seem to be empty, meaning that I can see through the mac block's bottom even though there are other blocks beneth it. Directly seeing the ocean

**Comment by Compbuild** [comment]
Minecraft issue called "culling" you can try going to Blockbench's Discord or try reporting the error to Minecraft (they'll probably ignore it).

**Comment by chahorain** [comment]
Ouch. But technically if I want to replace the model, just go Blocks folder and add two json files for the block that I want to replace?

**Comment by Compbuild** [comment]
Yes. Sorry for the late reply.

**Comment by chahorain** [comment]
No worries at all, you are being very patient and responsive, thank you so much!

**Comment by chahorain** [comment]
I successfully move mac and office chair to a trap door's bottom and up json. Culling issue is gone
